# Generated by Codex for the initial DescribeOps Django Ninja backend.

from __future__ import annotations

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_url", models.URLField(blank=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("page_title", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("created", "Created"), ("processing", "Processing"), ("ready", "Ready"), ("failed", "Failed")], default="created", max_length=24)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="VideoChunk",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("chunk_index", models.PositiveIntegerField()),
                ("start_seconds", models.FloatField()),
                ("end_seconds", models.FloatField()),
                ("transcript_text", models.TextField(blank=True)),
                ("capture_notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("accepted", "Accepted"), ("analyzing", "Analyzing"), ("ready", "Ready"), ("failed", "Failed")], default="accepted", max_length=24)),
                ("error_message", models.TextField(blank=True)),
                ("qwen_request_ids", models.JSONField(blank=True, default=list)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="reader.videosession")),
            ],
            options={"ordering": ["chunk_index"], "unique_together": {("session", "chunk_index")}},
        ),
        migrations.CreateModel(
            name="FrameAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.ImageField(upload_to="frames/%Y/%m/%d")),
                ("mime_type", models.CharField(max_length=80)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chunk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="frames", to="reader.videochunk")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=120)),
                ("prompt_version", models.CharField(max_length=80)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("output", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                ("latency_ms", models.PositiveIntegerField()),
                ("request_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chunk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_runs", to="reader.videochunk")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="ReadingBlock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField()),
                ("kind", models.CharField(choices=[("intro", "Intro"), ("explanation", "Explanation"), ("example", "Example"), ("code", "Code"), ("visual_context", "Visual context"), ("quote", "Quote"), ("demo_step", "Demo step"), ("timestamp_anchor", "Timestamp anchor"), ("takeaway", "Takeaway")], max_length=40)),
                ("heading", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                ("start_seconds", models.FloatField()),
                ("end_seconds", models.FloatField()),
                ("source_evidence", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.0)),
                ("is_user_edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reading_blocks", to="reader.videochunk")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reading_blocks", to="reader.videosession")),
            ],
            options={"ordering": ["order", "start_seconds"]},
        ),
        migrations.CreateModel(
            name="TimelineMoment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp_seconds", models.FloatField()),
                ("label", models.CharField(max_length=300)),
                ("detail", models.TextField(blank=True)),
                ("importance", models.PositiveSmallIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chunk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="timeline_moments", to="reader.videochunk")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="timeline_moments", to="reader.videosession")),
            ],
            options={"ordering": ["timestamp_seconds", "created_at"]},
        ),
        migrations.CreateModel(
            name="SessionEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="reader.videosession")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="UserCorrection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("previous_body", models.TextField()),
                ("corrected_body", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("block", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="corrections", to="reader.readingblock")),
            ],
        ),
    ]

