# Generated by Django 5.2.15 on 2026-06-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='source_url',
            field=models.TextField(blank=True),
        ),
    ]
