# Generated by Django 5.2.15 on 2026-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_pipeline_state_and_artifact_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochunk',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='accepted', max_length=24),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='created', max_length=24),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session', 'id'], name='event_session_id_idx'),
        ),
        migrations.AddIndex(
            model_name='videosession',
            index=models.Index(fields=['-created_at'], name='session_created_desc'),
        ),
    ]
