# Generated by Codex on 2026-06-25

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0005_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("job_type", models.CharField(choices=[("url_ingest", "URL ingest"), ("file_ingest", "File ingest"), ("chunk_analysis", "Chunk analysis"), ("synthesis_retry", "Synthesis retry")], db_index=True, max_length=40)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], db_index=True, default="queued", max_length=24)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=2)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="processing_jobs", to="reader.videosession")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["status", "created_at"], name="job_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["session", "status"], name="job_session_status_idx"),
        ),
    ]
