# Generated by Codex on 2026-06-26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0008_accounts_and_session_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalVideo",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fingerprint", models.CharField(db_index=True, max_length=96, unique=True)),
                ("canonical_url", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="videosession",
            name="source_fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=96),
        ),
        migrations.AddField(
            model_name="videosession",
            name="canonical_video",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sessions", to="reader.canonicalvideo"),
        ),
        migrations.CreateModel(
            name="StoredAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("source_video", "Source video"),
                            ("audio_chunk", "Audio chunk"),
                            ("transcript", "Transcript"),
                            ("frame", "Frame"),
                            ("qwen_output", "Qwen output"),
                            ("evidence_manifest", "Evidence manifest"),
                            ("final_artifact", "Final artifact"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("object_key", models.CharField(db_index=True, max_length=900)),
                ("storage_backend", models.CharField(default="default", max_length=80)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("agent_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="stored_assets", to="reader.agentrun")),
                ("artifact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="stored_assets", to="reader.generatedartifact")),
                ("canonical_video", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="reader.canonicalvideo")),
                ("chunk", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="stored_assets", to="reader.videochunk")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="stored_assets", to="reader.videosession")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="storedasset",
            index=models.Index(fields=["session", "asset_type"], name="asset_session_type_idx"),
        ),
        migrations.AddIndex(
            model_name="storedasset",
            index=models.Index(fields=["canonical_video", "asset_type"], name="asset_video_type_idx"),
        ),
    ]
