from __future__ import annotations

from reader.models import GeneratedArtifact, VideoSession
from reader.services.export import export_reading_document_markdown
from reader.services.timecode import format_timestamp

WORKFLOW_LABELS: dict[str, str] = {
    "reading_document": "Reading Document",
    "course_notes": "Course Notes",
    "audio_description": "Audio Description Script",
    "tutorial_extraction": "Developer Tutorial",
    "compliance_report": "Compliance Review",
    "video_to_document": "Video-to-Document",
    "meeting_reconstruction": "Meeting / Demo Reconstruction",
    "assistive_cues": "Assistive Companion Cues",
    "research_digest": "Research Digest",
    "localization_brief": "Localization Prep",
}

WORKFLOW_TO_ARTIFACT_TYPE: dict[str, str] = {
    "reading_document": GeneratedArtifact.ArtifactType.READING_DOCUMENT,
    "course_notes": GeneratedArtifact.ArtifactType.COURSE_NOTES,
    "audio_description": GeneratedArtifact.ArtifactType.AUDIO_DESCRIPTION,
    "tutorial_extraction": GeneratedArtifact.ArtifactType.TUTORIAL_EXTRACTION,
    "compliance_report": GeneratedArtifact.ArtifactType.COMPLIANCE_REPORT,
    "video_to_document": GeneratedArtifact.ArtifactType.MARKDOWN_EXPORT,
    "meeting_reconstruction": GeneratedArtifact.ArtifactType.MEETING_RECONSTRUCTION,
    "assistive_cues": GeneratedArtifact.ArtifactType.ASSISTIVE_CUES,
    "research_digest": GeneratedArtifact.ArtifactType.RESEARCH_DIGEST,
    "localization_brief": GeneratedArtifact.ArtifactType.LOCALIZATION_BRIEF,
}

WORKFLOW_IDS = frozenset(WORKFLOW_TO_ARTIFACT_TYPE)


def normalize_workflow_targets(primary: str, requested: list[str] | None = None) -> list[str]:
    targets: list[str] = []
    for workflow in [primary, *(requested or [])]:
        if workflow not in WORKFLOW_IDS:
            raise ValueError(f"Unsupported workflow template: {workflow}")
        if workflow not in targets:
            targets.append(workflow)
    return targets


def build_artifact_from_session(
    session: VideoSession,
    workflow_template: str = "reading_document",
    synthesis_result: dict | None = None,
) -> GeneratedArtifact:
    blocks = list(session.reading_blocks.order_by("order", "start_seconds"))
    moments = list(session.timeline_moments.order_by("timestamp_seconds"))

    artifact_type = WORKFLOW_TO_ARTIFACT_TYPE.get(workflow_template, GeneratedArtifact.ArtifactType.READING_DOCUMENT)
    title = session.title or session.page_title or "Untitled Video"
    sections: list = []

    if synthesis_result and not synthesis_result.get("skipped"):
        synth_title = synthesis_result.get("title") or title
        summary = synthesis_result.get("summary") or ""
        sections = synthesis_result.get("sections") or []
        payload: dict = {"sections": sections, "synthesis": synthesis_result}
    else:
        synth_title = title
        summary = _auto_summary(blocks)
        payload = {}

    markdown = (
        _render_synthesized_markdown(session, workflow_template, synth_title, summary, sections)
        if synthesis_result and sections
        else _render_markdown(session, blocks, moments, workflow_template, summary)
    )

    artifact, _created = GeneratedArtifact.objects.update_or_create(
        session=session,
        workflow_template=workflow_template,
        defaults={
            "artifact_type": artifact_type,
            "title": synth_title,
            "summary": summary,
            "markdown": markdown,
            "payload": payload,
        },
    )
    return artifact


def _render_synthesized_markdown(
    session: VideoSession,
    workflow_template: str,
    title: str,
    summary: str,
    sections: list,
) -> str:
    label = WORKFLOW_LABELS.get(workflow_template, "Reading Document")
    lines = [f"# {label} — {title}", ""]
    if summary:
        lines += [summary, ""]
    if session.source_url:
        lines += [f"**Source:** {session.source_url}", ""]
    for raw in sections:
        if not isinstance(raw, dict):
            continue
        heading = str(raw.get("heading") or "Section")
        body = str(raw.get("body") or "").strip()
        kind = str(raw.get("kind") or "explanation")
        start = float(raw.get("start_seconds") or 0)
        end = float(raw.get("end_seconds") or start)
        lines += [f"## {heading}", f"*{format_timestamp(start)}–{format_timestamp(end)} · {kind.replace('_', ' ').title()}*", ""]
        if kind == "code" and not body.startswith("```"):
            lines += ["```", body, "```", ""]
        else:
            lines += [body, ""]
    lines += ["---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)


def _auto_summary(blocks: list) -> str:
    intro = [b for b in blocks if b.kind == "intro"]
    takeaways = [b for b in blocks if b.kind == "takeaway"]
    candidates = intro[:1] + takeaways[:2]
    if not candidates:
        candidates = blocks[:2]
    return " ".join(b.body[:200] for b in candidates).strip()


def _render_markdown(session: VideoSession, blocks: list, moments: list, workflow_template: str, summary: str) -> str:
    if workflow_template == "reading_document":
        return export_reading_document_markdown(session)

    if workflow_template == "course_notes":
        return _render_course_notes(session, blocks, summary)

    if workflow_template == "video_to_document":
        return _render_article(session, blocks, summary)

    if workflow_template == "audio_description":
        return _render_audio_description(session, blocks, moments)

    if workflow_template == "tutorial_extraction":
        return _render_tutorial(session, blocks, moments)

    if workflow_template == "compliance_report":
        return _render_compliance(session, blocks, moments)

    if workflow_template == "meeting_reconstruction":
        return _render_meeting(session, blocks, moments)

    if workflow_template == "assistive_cues":
        return _render_assistive_cues(session, moments, blocks)

    if workflow_template == "research_digest":
        return _render_research(session, blocks, moments)

    if workflow_template == "localization_brief":
        return _render_localization(session, blocks, moments)

    return export_reading_document_markdown(session)


def _render_course_notes(session: VideoSession, blocks: list, summary: str) -> str:
    lines = [f"# Course Notes — {session.title or 'Untitled'}", ""]
    if summary:
        lines += ["## Overview", "", summary, ""]
    for block in blocks:
        lines += [f"## {block.heading or block.kind.replace('_', ' ').title()}", f"*{format_timestamp(block.start_seconds)}*", "", block.body, ""]
    return "\n".join(lines)


def _render_article(session: VideoSession, blocks: list, summary: str) -> str:
    lines = [f"# {session.title or 'Untitled'}", ""]
    if summary:
        lines += [summary, ""]
    for block in blocks:
        if block.heading:
            lines += [f"## {block.heading}", ""]
        lines += [block.body, ""]
    return "\n".join(lines)


def _render_audio_description(session: VideoSession, blocks: list, moments: list) -> str:
    lines = [f"# Audio Description Script — {session.title or 'Untitled'}", ""]
    if session.source_url:
        lines += [f"**Source:** {session.source_url}", ""]
    lines += ["## Spoken Cues", ""]
    for block in blocks:
        if block.kind in ("visual_context", "intro", "explanation", "demo_step"):
            ts = format_timestamp(block.start_seconds)
            lines.append(f"**[{ts}]** {block.body}")
            lines.append("")
    lines += ["---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)


def _render_tutorial(session: VideoSession, blocks: list, moments: list) -> str:
    lines = [f"# Developer Tutorial — {session.title or 'Untitled'}", ""]
    code_blocks = [b for b in blocks if b.kind == "code"]
    demo_steps = [b for b in blocks if b.kind == "demo_step"]
    others = [b for b in blocks if b.kind not in ("code", "demo_step")]

    if demo_steps:
        lines += ["## Steps", ""]
        for i, b in enumerate(demo_steps, 1):
            lines.append(f"### Step {i} — {b.heading or format_timestamp(b.start_seconds)}")
            lines.append(b.body)
            lines.append("")

    if code_blocks:
        lines += ["## Code & Commands", ""]
        for b in code_blocks:
            if b.heading:
                lines.append(f"### {b.heading}")
            lines += ["```", b.body, "```", ""]

    if others:
        lines += ["## Notes", ""]
        for b in others:
            if b.heading:
                lines.append(f"### {b.heading}")
            lines.append(b.body)
            lines.append("")

    lines += ["---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)


def _render_compliance(session: VideoSession, blocks: list, moments: list) -> str:
    lines = [f"# Accessibility Compliance Review — {session.title or 'Untitled'}", ""]
    visual_ctx = [b for b in blocks if b.kind == "visual_context"]
    low_confidence = [b for b in blocks if b.confidence < 0.5]
    lines += ["## Visual Context Blocks", ""]
    if visual_ctx:
        for b in visual_ctx:
            lines.append(f"- **[{format_timestamp(b.start_seconds)}]** {b.body[:300]}")
    else:
        lines.append("- No visual context blocks detected.")
    lines += ["", "## Low-Confidence Segments", ""]
    if low_confidence:
        for b in low_confidence:
            lines.append(f"- **[{format_timestamp(b.start_seconds)}]** (conf: {b.confidence:.2f}) {b.heading or b.body[:120]}")
    else:
        lines.append("- All segments met confidence threshold.")
    lines += ["", "---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)


def _render_meeting(session: VideoSession, blocks: list, moments: list) -> str:
    lines = [f"# Meeting / Demo Reconstruction — {session.title or 'Untitled'}", ""]
    if moments:
        lines += ["## Timeline", ""]
        for m in moments:
            lines.append(f"- **[{format_timestamp(m.timestamp_seconds)}]** {m.label}")
            if m.detail:
                lines.append(f"  {m.detail}")
        lines.append("")
    demo_steps = [b for b in blocks if b.kind == "demo_step"]
    if demo_steps:
        lines += ["## Demo Steps", ""]
        for b in demo_steps:
            lines.append(f"### {b.heading or format_timestamp(b.start_seconds)}")
            lines.append(b.body)
            lines.append("")
    takeaways = [b for b in blocks if b.kind == "takeaway"]
    if takeaways:
        lines += ["## Key Takeaways / Action Items", ""]
        for b in takeaways:
            lines.append(f"- {b.body}")
        lines.append("")
    lines += ["---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)


def _render_assistive_cues(session: VideoSession, moments: list, blocks: list) -> str:
    lines = [f"# Assistive Companion Cues — {session.title or 'Untitled'}", ""]
    all_cues: list[tuple[float, str]] = []
    for m in moments:
        all_cues.append((m.timestamp_seconds, m.label + (f" — {m.detail}" if m.detail else "")))
    for b in blocks:
        if b.kind in ("visual_context", "demo_step"):
            all_cues.append((b.start_seconds, b.body[:200]))
    all_cues.sort(key=lambda x: x[0])
    for ts, text in all_cues:
        lines.append(f"**[{format_timestamp(ts)}]** {text}")
        lines.append("")
    lines += ["---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)


def _render_research(session: VideoSession, blocks: list, moments: list) -> str:
    lines = [f"# Research Digest — {session.title or 'Untitled'}", ""]
    quotes = [b for b in blocks if b.kind == "quote"]
    examples = [b for b in blocks if b.kind == "example"]
    takeaways = [b for b in blocks if b.kind == "takeaway"]
    if quotes:
        lines += ["## Key Quotes", ""]
        for b in quotes:
            for ql in b.body.split("\n"):
                lines.append(f"> {ql}")
            lines.append("")
    if examples:
        lines += ["## Examples & Evidence", ""]
        for b in examples:
            lines.append(f"- **[{format_timestamp(b.start_seconds)}]** {b.body[:300]}")
        lines.append("")
    if takeaways:
        lines += ["## Key Findings", ""]
        for b in takeaways:
            lines.append(f"- {b.body}")
        lines.append("")
    lines += ["## Full Timeline", ""]
    for m in moments:
        lines.append(f"- **[{format_timestamp(m.timestamp_seconds)}]** {m.label}")
    lines += ["", "---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)


def _render_localization(session: VideoSession, blocks: list, moments: list) -> str:
    lines = [f"# Localization Brief — {session.title or 'Untitled'}", ""]
    if session.source_url:
        lines += [f"**Source:** {session.source_url}", ""]
    lines += ["## Translatable Script Segments", ""]
    for b in blocks:
        ts = format_timestamp(b.start_seconds)
        te = format_timestamp(b.end_seconds)
        lines.append(f"### [{ts} – {te}] {b.heading or b.kind.replace('_', ' ').title()}")
        lines.append(b.body)
        lines.append("")
    if moments:
        lines += ["## Timeline Labels (for localization)", ""]
        for m in moments:
            lines.append(f"- **[{format_timestamp(m.timestamp_seconds)}]** {m.label}")
        lines.append("")
    lines += ["---", "*Generated by DescribeOps*", ""]
    return "\n".join(lines)
