from __future__ import annotations

from reader.models import VideoSession
from reader.services.timecode import format_timestamp


def export_reading_document_markdown(session: VideoSession) -> str:
    blocks = list(session.reading_blocks.order_by("order", "start_seconds"))
    moments = list(session.timeline_moments.order_by("timestamp_seconds"))

    lines: list[str] = []
    lines.append(f"# {session.title or session.page_title or 'Untitled Video'}")
    lines.append("")
    if session.source_url:
        lines.append(f"**Source:** {session.source_url}")
    if session.duration_seconds:
        lines.append(f"**Duration:** {format_timestamp(session.duration_seconds)}")
    lines.append(f"**Generated:** {session.updated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    if moments:
        lines.append("## Timeline")
        lines.append("")
        for moment in moments:
            lines.append(f"- **{format_timestamp(moment.timestamp_seconds)}** — {moment.label}")
            if moment.detail:
                lines.append(f"  {moment.detail}")
        lines.append("")

    lines.append("## Reading Document")
    lines.append("")

    current_heading = ""
    for block in blocks:
        time_label = f"[{format_timestamp(block.start_seconds)}]"
        if block.heading and block.heading != current_heading:
            current_heading = block.heading
            lines.append(f"### {block.heading} {time_label}")
            lines.append("")

        if block.kind == "code":
            lines.append(f"```")
            lines.append(block.body)
            lines.append(f"```")
        elif block.kind == "quote":
            for quote_line in block.body.split("\n"):
                lines.append(f"> {quote_line}")
        else:
            lines.append(block.body)
        lines.append("")

    lines.append("---")
    lines.append("*Generated by DescribeOps — AI video reading layer*")
    lines.append("")
    return "\n".join(lines)
